---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-cloud-gateway
  namespace: gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spring-cloud-gateway
rules:
- apiGroups:
  - gateway.cloud.ik.am
  resources:
  - routedefinitions
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - services
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gateway-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spring-cloud-gateway
subjects:
- kind: ServiceAccount
  name: spring-cloud-gateway
  namespace: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-gateway
  namespace: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-cloud-gateway
  template:
    metadata:
      labels:
        app: spring-cloud-gateway
    spec:
      serviceAccountName: spring-cloud-gateway
      containers:
      - image: making/kubernetes-spring-cloud-gateway:latest
        name: spring-cloud-gateway
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: BPL_THREAD_COUNT
          value: "36"
        - name: JAVA_OPTS
          value: " -XX:ReservedCodeCacheSize=32M -Xss512k -XX:+PrintCodeCache"
        - name: SPRING_SLEUTH_SAMPLER_RATE
          value: "30"
        - name: SPRING_ZIPKIN_BASE_URL
          value: https://zipkin.apps.pcfone.io
        - name: SPRING_SLEUTH_WEB_ADDITIONAL_SKIP_PATTERN
          value: "/management.*,/actuator.*"
        - name: SPRING_SLEUTH_SCHEDULED_SKIP_PATTERN
          value: am.ik.cloud.gateway.locator.KubernetesRouteDefinitionLocator
        - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH
          value: "/management"
        - name: LOGGING_EXCEPTION_CONVERSION_WORD
          value: "\t%replace(%replace(%xEx){'\n','@n@'}){'\t','    '}%nopex"
        - name: LOGGING_PATTERN_CONSOLE
          value: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${logging.pattern.level:%5p}) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %replace(%m){'\n','@n@'}${logging.exception-conversion-word:%wEx}%n"
        - name: INFO_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INFO_K8S_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INFO_K8S_APP
          value: "${spring.application.name}"
        - name: MANAGEMENT_METRICS_TAGS_ORGANIZATION
          value: cfcr-aws
        - name: MANAGEMENT_METRICS_TAGS_SPACE
          value: "${INFO_K8S_NAMESPACE}"
        - name: MANAGEMENT_METRICS_TAGS_APPLICATION
          value: "${INFO_K8S_APP}"
        - name: MANAGEMENT_METRICS_TAGS_INSTANCE_ID
          value: "${INFO_K8S_POD}"          
        resources:
          limits:
            memory: "300Mi"
          requests:
            memory: "300Mi"
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8080
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /management/info
            port: 8080
            scheme: HTTPS
          initialDelaySeconds: 180
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
---
kind: Service
apiVersion: v1
metadata:
  name: spring-cloud-gateway
  namespace: gateway
  labels:
    app: spring-cloud-gateway
spec:
  type: NodePort
  selector:
    app: spring-cloud-gateway
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 32765
    name: https
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: spring-cloud-gateway
  namespace: gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: spring-cloud-gateway
