name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.x'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: mvn package
      if: github.ref == 'refs/heads/master'
      run: |
        set -e
        BOOT_VERSION=$(grep '<version>' pom.xml | head -n 2 | tail -n 1 | sed -e 's|<version>||g' -e 's|</version>||g' -e 's| ||g' |  tr -d '\t')
        ./mvnw -V package -Dmaven.test.skip=true -Dspring-boot.version=${BOOT_VERSION}
    - name: pack build
      if: github.ref == 'refs/heads/master'
      env:
        PACK_VERSION: 0.10.0
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        set -e
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        wget -q https://github.com/buildpacks/pack/releases/download/v${PACK_VERSION}/pack-v${PACK_VERSION}-linux.tgz
        tar xzf pack-*.tgz
        rm -f pack-*.tgz
        ./pack build making/kubernetes-spring-cloud-gateway \
          -p target/gateway-*.jar  \
          --builder cloudfoundry/cnb:bionic \
          --publish
    - uses: azure/k8s-set-context@v1
      if: github.ref == 'refs/heads/master'
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - name: kubectl apply
      if: github.ref == 'refs/heads/master'
      env:
        KBLD_VERSION: 0.13.0
        WAIT_UNTIL_READY_SELECTOR: app=spring-cloud-gateway
      run: |
        set -e
        wget -q https://github.com/k14s/kbld/releases/download/v${KBLD_VERSION}/kbld-linux-amd64 -O kbld
        chmod +x kbld
        ./kbld -f k8s | kubectl apply -f -
        wget -q https://raw.githubusercontent.com/zlabjp/kubernetes-resource/master/assets/common.sh
        source common.sh
        wait_until_pods_ready 120 5 ${WAIT_UNTIL_READY_SELECTOR}
